Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/fracchio/.espressif/python_env/idf5.2_py3.11_env/lib64/python3.11/site-packages/esptool/__main__.py", line 9, in <module>
    esptool._main()
  File "/home/fracchio/.espressif/python_env/idf5.2_py3.11_env/lib64/python3.11/site-packages/esptool/__init__.py", line 1139, in _main
    main()
  File "/home/fracchio/.espressif/python_env/idf5.2_py3.11_env/lib64/python3.11/site-packages/esptool/__init__.py", line 712, in main
    esp = esp or get_default_connected_device(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fracchio/.espressif/python_env/idf5.2_py3.11_env/lib64/python3.11/site-packages/esptool/__init__.py", line 1023, in get_default_connected_device
    _esp = chip_class(each_port, initial_baud, trace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fracchio/.espressif/python_env/idf5.2_py3.11_env/lib64/python3.11/site-packages/esptool/loader.py", line 303, in __init__
    self._port = serial.serial_for_url(port)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fracchio/.espressif/python_env/idf5.2_py3.11_env/lib64/python3.11/site-packages/serial/__init__.py", line 90, in serial_for_url
    instance.open()
  File "/home/fracchio/.espressif/python_env/idf5.2_py3.11_env/lib64/python3.11/site-packages/serial/serialposix.py", line 338, in open
    self._update_rts_state()
  File "/home/fracchio/.espressif/python_env/idf5.2_py3.11_env/lib64/python3.11/site-packages/serial/serialposix.py", line 706, in _update_rts_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_RTS_str)
TimeoutError: [Errno 110] Connection timed out
CMake Error at run_serial_tool.cmake:66 (message):
  
  /home/fracchio/.espressif/python_env/idf5.2_py3.11_env/bin/python;;/home/fracchio/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32s3
  failed.



